print("My name is Hamza Jadoon and I belong fro Pakistan.")
print("I am in 1st year, I have 2 siblings.")
print("My favourite color is blue.")
print("My favourite game is Football.")
print("Till now I have a very good experience with codingal.")